### ISSUE TITLE
PublishADFTask@1 DevOps task does not work on Linux agent

### ISSUE THREAD

**Issue by andrewwwooster** [SQLPlayer/azure.datafactory.devops#102]
The Power Shell Publish-AdfV2FromJson command works well on a Linux DevOps agent with Power Shell Core installed.  However, for some reason, the DevOps PublishADFTask@1 task reports the following error when running on a Linux agent:

`The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.`

**Comment by NowinskiK** [comment]
I'm closing this as a duplicated issue to this one: #64
Consider using PowerShell Module of #adftools instead of AzureDevOps if you need to run under a Linux agent.
