### ISSUE TITLE
The column "Value" does not support array variables while deploying

### ISSUE THREAD

**Issue by akhila31** [SQLPlayer/azure.datafactory.devops#104]
We are using array variables in ADF pipelines which looks like this for ex [{"A":"B", "C","D"}] 

While deploying the code we are getting "Unexpected token" . Will this feature be added in the future?

**Comment by NowinskiK** [comment]
That is NOT valid array:
![image](https://user-images.githubusercontent.com/25029325/194166094-9d05f87e-bb36-4198-ba02-2def2563e4b1.png)

![image](https://user-images.githubusercontent.com/25029325/194166139-75d76661-2989-467c-a037-27630d324c87.png)
