### ISSUE TITLE
Understand linked service overrides in config file

### ISSUE THREAD

**Issue by Oz1257** [SQLPlayer/azure.datafactory.devops#107]
I have been trying to override a linked service parameter defaults getting this error, is this even possible?

2022-10-20T13:57:24.8754926Z ##[error]ADFT0010: **Wrong path defined in config for object(path): linkedService.ls_AzureFunction(properties.functionAppUrl.defaultValue**)
2022-10-20T13:57:24.9294082Z ##[section]Finishing: Publish ADF adf-kws-qa01 from JSON files
Also tried 
2022-10-20T13:36:28.4789277Z ##[error]ADFT0010: **Wrong path defined in config for object(path): linkedService.ls_AzureFunction(properties.parameters.functionAppSecretKey.defaultValue)**
2022-10-20T13:36:28.5503917Z ##[section]Finishing: Publish ADF adf-kws-qa01 from JSON files

linkedService,ls_AzureFunction,properties.parameters.functionAppUrl.defaultValue,"https://func-dna-qa01.azurewebsites.net"
linkedService,ls_AzureFunction,properties.parameters.functionAppSecretKey.defaultValue,"func-dna-master-key-uat"

linkedService,ls_AzureFunction,properties.functionAppUrl.defaultValue,"https://func-dna-qa01.azurewebsites.net"
linkedService,ls_AzureFunction,properties.functionAppSecretKey.defaultValue,"func-dna-master-key-uat"

Linked Service Json
{
    "name": "ls_AzureFunction",
    "properties": {
        "parameters": {
            "functionAppUrl": {
                "type": "String",
                "defaultValue": "https://func-dna-dev01.azurewebsites.net"
            },
            "funcAppSecretKey": {
                "type": "string",
                "defaultValue": "func-dna-master-key-uat"
            }
        },
        "annotations": [],
        "type": "AzureFunction",
        "typeProperties": {
            "functionAppUrl": "@{linkedService().functionAppUrl}",
            "functionKey": {
                "type": "AzureKeyVaultSecret",
                "store": {
                    "referenceName": "ls_kv_dna",
                    "type": "LinkedServiceReference"
                },
                "secretName": {
                    "value": "@linkedService().funcAppSecretKey",
                    "type": "Expression"
                }
            },
            "authentication": "Anonymous"
        },
        "connectVia": {
            "referenceName": "AutoResolveIntegrationRuntime",
            "type": "IntegrationRuntimeReference"
        }
    },
    "type": "Microsoft.DataFactory/factories/linkedservices"
}

**Comment by NowinskiK** [comment]
![image](https://user-images.githubusercontent.com/25029325/197058571-163bc869-148e-49d6-903f-92bb0146287d.png)
