### ISSUE TITLE
Selective Deployment from specific folder

### ISSUE THREAD

**Issue by ShafeekSaleem** [SQLPlayer/azure.datafactory.devops#14]
How to include only the pipelines from specific folder?

Lets say my adf has pipelines inside two folders as A and B. How can I deploy only the pipelines from the folder A?

**Comment by NowinskiK** [comment]
That option is not yet supported by Azure DevOps Task (but it exists in [PS module](https://github.com/SQLPlayer/azure.datafactory.tools))
It will be available this year along with public version 1.0, which is planned for Dec 2020.

**Comment by ShafeekSaleem** [comment]
Thanks for the headsup, and Since I'm new to this PS module, can I do this in azure devops release pipeline using PS module? not locally.

**Comment by santoshdata** [comment]
I also came across of similar requirements for pipeline, dataset and data flow

**Comment by ShafeekSaleem** [comment]
@santoshdata  As @NowinskiK suggested, I went with the PS module which has lots of flexibilities. You can select pipelines, datasets by folders and then deploy them onto the environment.

**Comment by ShafeekSaleem** [comment]
Between @NowinskiK Thank you for ur response earlier. I forgot to thank you😊

**Comment by NowinskiK** [comment]
@ShafeekSaleem no problem at all. Thanks.
That's true - PS offers a lot of flexibility, however, the extension task is just UI on top of that and should offer exactly the same capabilities. 
The plan is to enhance the current feature of selecting objects.
The following pattern: `+obj_type.obj_name` will be extended to that `+obj_type.obj_name@folder_name`
