### ISSUE TITLE
File Path Filtering Type not working

### ISSUE THREAD

**Issue by stlhiers** [SQLPlayer/azure.datafactory.devops#17]
Thanks for developing this great tool. It will make our lives so much easier.

I'm having some trouble with filtering.  Filtering works fine with the inline option, but I can't get it to work with the "file path" option. I've tried a number of configurations but the release always runs without copying anything.

Currently I have a rules.txt file in the ./deployment folder (same as used for the Environment Config). I confirmed that the file uses UTF-8 encoding and I have one object on per line. The content of the file is exactly the same that which works when pasted into the  include/exclude box when using the inline option.

The pipelines do have spaces in the name. I've tried with and without brackets around the pipeline name. Neither works. Here they are:

+pipeline.RPG - Test Pipe
+pipeline.RPG2 - Test Pipe

What am I missing?

**Comment by NowinskiK** [comment]
Hi @stlhiers, thanks for using the tool and your kind words!  
I'm glad that you mentioned about file encoding as UTF8 is required. 
Could you attach your `rules.txt` file where you have all definitions? If you could paste the log - that would be useful as well.

**Comment by stlhiers** [comment]
Here is the rules file and the log.  Thanks.

[tasklog_8.log](https://github.com/SQLPlayer/azure.datafactory.devops/files/5645939/tasklog_8.log)
[rules.txt](https://github.com/SQLPlayer/azure.datafactory.devops/files/5645940/rules.txt)
