### ISSUE TITLE
New version breaks Ci/CD as it requires Az.Accounts version 3.0.4

### ISSUE THREAD

**Issue by irisc387** [SQLPlayer/azure.datafactory.devops#170]
_"This module requires Az.Accounts version 3.0.4. An earlier version of Az.Accounts is imported in the current PowerShell session."_

**Comment by NowinskiK** [comment]
What's your Agent's image version? Is it Microsoft or a self-hosted agent?
The new version has been tested on Microsoft hosted agent running on Microsoft Windows Server 2022 (windows-2022 or windows-latest image), which already contains this version of Az.Accounts PowerShell module.
