### ISSUE TITLE
could not find object: factory

### ISSUE THREAD

**Issue by stlhiers** [SQLPlayer/azure.datafactory.devops#21]
I'm attempting to update the global variable of the target data factory. I have the following row in the config-test.csv:
factory,"mh-test-adf-simpledeployment","$.properties.globalParameters.'environment'.value","test"

When I run the release I get this error:
[error]Could not find object: factory.mh-test-adf-simpledeployment

**Comment by NowinskiK** [comment]
Can you provide a compressed zip file with this code of ADF? Then I would be able to reproduce the steps.

**Comment by stlhiers** [comment]
Is it the ARM template for the target ADF you need?

**Comment by NowinskiK** [comment]
No, the source JSON files that you're trying to deploy, located in your repo.

**Comment by stlhiers** [comment]
I think I got it figured out. Thanks.
