### ISSUE TITLE
Cannot run task on Linux based agent

### ISSUE THREAD

**Issue by dawid-gupta** [SQLPlayer/azure.datafactory.devops#24]
I have problems with running ADF deployment using Azure devops task you have created running Linux self-hosted agent (it neither works ok MS-hosted Linux agent). I got error "The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell." 
When I open pwsh on that agent and run the powershell script manually (Publish-AdfV2FromJson), deployment finishes successfully. Any tip ?

**Comment by NowinskiK** [comment]
hey @dawid-gupta. Currently, the extension is compatible with Windows-based agents only, I'm afraid. 
It's not easy thing to do as agents (even if have PowerShell Core) don't have PSCore handler to support extensions written in PowerShell.
[VSTS build task extension based on PowerShell Script not running on Linux/MacOS hosted agents #1416](https://github.com/microsoft/azure-pipelines-agent/issues/1416)

**Comment by NowinskiK** [comment]
Such version may appear in the future, but I don't have this in the nearest plans.
For the record:
[A technique for porting PowerShell based Azure DevOps Extensions to Node](https://blogs.blackmarble.co.uk/rfennell/2019/12/28/a-technique-for-porting-powershell-based-azure-devops-extensions-to-node-so-they-can-be-run-cross-platform-without-a-complete-re-write/)
