### ISSUE TITLE
On the Azure DevOps extension is the DeployGlobalParams option available?

### ISSUE THREAD

**Issue by estevebc** [SQLPlayer/azure.datafactory.devops#28]
On the PowerShell module documentation there is the following Publish Option **DeployGlobalParams** which the documentation states: "[Boolean] DeployGlobalParams - indicates whether deploy Global Parameters of ADF. Nothing happens when parameters are not defined. (default: true)"
Nevetheless, using the Azure DevOps extension, it seems there is no way to control the DeployGlobalParams

Thanks

**Comment by NowinskiK** [comment]
Azure DevOps extension doesn't support that flag - so it always deploys Global Params.
When it comes to the module - I can't see any problem with that and the option should works. 
If you face any issue with that - do raise new issue: https://github.com/SQLPlayer/azure.datafactory.tools/issues
adding logs and a subset of your code which allows me to reproduce the error.

**Comment by NowinskiK** [comment]
However, you still can use filters to exclude Global Parameters from a deployment - that approach allows you to NOT deploy GPs.
