### ISSUE TITLE
Az.Resources PowerShell module error

### ISSUE THREAD

**Issue by benjarvis18** [SQLPlayer/azure.datafactory.devops#3]
Hi,

We're using the Azure DevOps task to deploy to an ADF instance but have begun getting the following error when trying to deploy. This was working around a week ago so it looks like a recent update has broken it:

##[error]The 'New-AzResource' command was found in the module 'Az.Resources', but the module could not be loaded. For more information, run 'Import-Module Az.Resources'.

This occurred when running on the windows-latest hosted agent.

**Comment by NowinskiK** [comment]
@benjarvis18, I will take a look at this tonight.
