### ISSUE TITLE
Issue in Publish ADF on choosing factory file or config file

### ISSUE THREAD

**Issue by kishbala** [SQLPlayer/azure.datafactory.devops#33]
Hi @NowinskiK 

Lately, when trying to create a release pipeline, I have noticed the following issue popping up. Not sure if this is happening for others. Can you able to fix it?

Tried using both version 0 and 1.

**Could not load file or assembly 'BuildXL.Cache.ContentStore.Hashing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6212d9137135ce5d' or one of its dependencies. The system cannot find the file specified.**

![Issue](https://user-images.githubusercontent.com/61445062/110968187-58f48c00-83ab-11eb-951b-a4e9989a0767.JPG)

Regards
Kishore

**Comment by NowinskiK** [comment]
It is not a problem with the task. It comes from Azure DevOps:
https://twitter.com/sqldbawithbeard/status/1369304056884305931

Raise a ticket to support.

**Comment by kishbala** [comment]
Hi @NowinskiK

Agree. The issue was with Azure DevOps since they were implementing some of the latest patches around certain regions. It was resolved after raising a ticket to Azure support. Thanks for your help.
