### ISSUE TITLE
Synapse support by "Publish Azure Data Factory"?

### ISSUE THREAD

**Issue by parasparekh** [SQLPlayer/azure.datafactory.devops#40]
Hello,
I am trying to use the adftools to deploy Azure Synapse data pipelines but my release is failing with the error that the ADF instance doesn't exist. I am using {synapsename}.{region}.datafactory.azure.net as the Target Azure Data Factory Name but the release fails. So I was wondering if this plug-in works for Azure Synapse Workspace or does it work only for Azure Data Factory. Any help or guidance would be highly appreciated.

**Comment by NowinskiK** [comment]
This extension doesn't not support Synapse.
See more: https://github.com/SQLPlayer/azure.datafactory.tools/issues/91

**Comment by parasparekh** [comment]
Are there plans for this extension to support incremental deployment of Synapse data pipelines and is there a timeline when Synapse will be supported ? Incremental deployment is the key feature of this extension and it is this feature that sets the extension apart from the Microsoft developed deployment tasks whether they are for Data Factory or Synapse.

**Comment by NowinskiK** [comment]
Synapse differs from ADF, hence it will be a separate task. Yes, there are plans for that, but I can't give an exact ETA. Probably Q3 of 2021 should be preview, but it depends how well Az.Synapse module is.

**Comment by parasparekh** [comment]
Sure, thank you Nowinski
