### ISSUE TITLE
Environment variable in config file & 'name' column 

### ISSUE THREAD

**Issue by ivankragh** [SQLPlayer/azure.datafactory.devops#41]
I get an error when using a environment variable together with a wildcard * as part of the file-name 
![image](https://user-images.githubusercontent.com/82568581/114827632-3ea63780-9dc9-11eb-83e6-8c37464126d3.png)

Azure DevOps Build Pipeline returns the following error: "##[error]ADFT0007: Could not find object: trigger.$($Env:Environment)*" 
![image](https://user-images.githubusercontent.com/82568581/114828276-ff2c1b00-9dc9-11eb-9be1-2d0e0a4ac6b6.png)
 
I have configured the environment variable in the Publish task:
![image](https://user-images.githubusercontent.com/82568581/114828664-795c9f80-9dca-11eb-8a2d-4eeae7ca2f06.png)

**Comment by NowinskiK** [comment]
Column [name] does not support env-variables. 
I think you have some edge case where you have triggers for various environment in one ADF. 
This is neither not typical, nor recommended.

**Comment by ivankragh** [comment]
Hi' Kamil I manged to create a work-around with simply adding a PowerShell task before the publish task where I remove triggers which is not associated with the specific environment i'm working on :

![image](https://user-images.githubusercontent.com/82568581/114944902-b8313a80-9e48-11eb-9b55-4236d168412b.png)

This technic allows for creating multiple triggers which then is associated with the specific environment from which DevOps Release pipeline is publishing to. When collecting all environment trigger configurations within the development branch it possible to run different sets of operations for different environments. 

### Development Branch
![image](https://user-images.githubusercontent.com/82568581/114945385-84a2e000-9e49-11eb-8808-10719c31560e.png)

### Published Development ADF
![image](https://user-images.githubusercontent.com/82568581/114945472-ac924380-9e49-11eb-88ff-75ecb394e918.png)

### Published User Acceptance Test ADF
![image](https://user-images.githubusercontent.com/82568581/114945559-d77c9780-9e49-11eb-89f5-ea4103253368.png)

With the latest CI/CD recommendations from MS it looks like the only way to securely handle environment specific triggers - do you have another suggestion ? :)

**Comment by NowinskiK** [comment]
@ivankragh, good job.
I have good news for you: you can leave all files where they are and EXCLUDES or INCLUDE selected file:
![image](https://user-images.githubusercontent.com/25029325/115025688-91f7b300-9eb9-11eb-94cb-e69a6da0cbd2.png)
Doc:
https://github.com/SQLPlayer/azure.datafactory.tools#filtering-file-example
