### ISSUE TITLE
Question: What is the difference between two publish methods (az.datafactory an az.resource) in advanced tab?

### ISSUE THREAD

**Issue by akhila31** [SQLPlayer/azure.datafactory.devops#42]
![image](https://user-images.githubusercontent.com/55212152/115129239-1ded0600-9fb2-11eb-9f79-40e2643cb0f0.png)

**Comment by NowinskiK** [comment]
Az.Resource method uses [Az.Resources module](https://docs.microsoft.com/en-us/powershell/module/az.resources/) to deploy all ADF objects (resources) one by one, whereas Az.DataFactory uses [Az.DataFactory module](https://docs.microsoft.com/en-us/powershell/module/az.datafactory/).
The difference is that Az.DataFactory parses the code (files) when pulling and posting from/to ADF instance, which sometimes may cause an error when the bug exists in the module for a specific configuration of an ADF object.
A few examples of such error:
[Treat as null parameters not working](https://github.com/SQLPlayer/azure.datafactory.tools/issues/11)
[Deployment of Wait Activity with expression fails with option DeleteNotInSource = $true](https://github.com/SQLPlayer/azure.datafactory.tools/issues/14)
["Unable to deserialize the response." issue with excluded objects](https://github.com/SQLPlayer/azure.datafactory.tools/issues/85)

That's the reason for using **Az.Resource** approach, which is generic for all Azure resources.
