### ISSUE TITLE
Issue in cherry pick deployment.

### ISSUE THREAD

**Issue by himmyaggarwal** [SQLPlayer/azure.datafactory.devops#44]
I am facing challenge in triggers deployment. I have a scenario where i have:

pipeline1 -> trigger1
pipeline2 -> trigger2
pipeline3 -> trigger3

I have above pipelines connected to their respective triggers.

I have disabled my trigger 3 because, i am just updating pipeline3 and trigger 3 but tool is asking to disable the trigger1 first for the deployment and failed with the same error.

Please help.

**Comment by NowinskiK** [comment]
What error?

**Comment by himmyaggarwal** [comment]
Task is trying to deploy all triggers. I just updated trigger 3, it's giving error for trigger1. 

is this like tool try to deploy all the triggers instead of deploying only which updated?

##[error]TriggerEnabledCannotUpdate : Cannot update enabled Trigger; the trigger needs to be disabled first.

**Comment by NowinskiK** [comment]
Yes, by default it deploys all objects of ADF. 
If you want to deploy selected objects only - filter those objects: 
https://github.com/SQLPlayer/azure.datafactory.tools#filtering-file-example
Check the documentation. The tool doesn't deploy only 'updated objects'.
