### ISSUE TITLE
Error: "Invalid Json Primitive: https." when trying to apply environment configurations via CSV or JSON

### ISSUE THREAD

**Issue by asherman-hsi** [SQLPlayer/azure.datafactory.devops#46]
Hello,

I'm looking to leverage this tool for pipeline deployment of our Azure Data Factory, but I'm having trouble with the stage configuration step of the task.  We've tried both a .csv and a .json configuration file, but in both cases we get the following error: 
"Invalid Json Primitive: https."

It appears that this happens when attempting to perform the replacement of the values to the actual json files.  We've verified our formatting versus the examples provided in the documentation and aren't sure why this isn't working for us.  Is there a way to get the debug output so we can determine which value is failing, specifically?  Any guidance on known formatting issues, possibly a special character problem?

Thanks.

**Comment by NowinskiK** [comment]
Add "system.debug" = "true" to Variables.
Debug mode should show more details.

**Comment by asherman-hsi** [comment]
Thanks Kamil,

To the pipeline variables or to the environment variables in the pipeline task?

Andrew Sherman
DevOps Manager/Security Officer

**Comment by asherman-hsi** [comment]
I figured out the debug variable and now I am troubleshooting new errors.  Thank you for that.  I will post my resolution once I have found it but I now suspect formatting errors on my part.

Andrew Sherman
DevOps Manager/Security Officer

**Comment by NowinskiK** [comment]
Great. I will close this issue now, however, please share your findings with us here.

**Comment by asherman-hsi** [comment]
Thanks.

Ultimately I had a formatting issue in my csv file, where I was not declaring the correct JSON element which created the mismatch.  Specifically, I was missing the “default value” element.
Hope this helps someone in the future.

Andrew Sherman
DevOps Manager/Security Officer

**Comment by NowinskiK** [comment]
Thanks @asherman-hsi !
