### ISSUE TITLE
Can not convert Object to String

### ISSUE THREAD

**Issue by SudhirNune** [SQLPlayer/azure.datafactory.devops#47]
During the deployment process of ADF, we are seeing the below error

Can not convert Object to String

The error occurs at the 
**STEP: Deleting objects not in source ...
Azure Data Factory (instance) loaded.**

**we see the following error:**
`##[debug]at Get-AdfFromService, D:\a\_tasks\PublishADFTask_XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\1.6.846**\ps_modules\azure.datafactory.tools\public\Get-AdfFromService.ps1: line 40**
##[debug]at Publish-AdfV2FromJson, D:\a\_tasks\PublishADFTask_XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\1.6.846\ps_modules\azure.datafactory.tools\public\Publish-AdfV2FromJson.ps1: line 195
##[debug]at <ScriptBlock>, D:\a\_tasks\PublishADFTask_XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\1.6.846\PublishADF.ps1: line 128
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.ArgumentException: Can not convert Object to String.`

Our ADF factory has **143 Data Sets**

**Comment by NowinskiK** [comment]
Log please

**Comment by SudhirNune** [comment]
Found the issue, this is a core issue with the command let of - **Get-AzDataFactoryV2Dataset**.

Raised a bug in Azure Power Shell Module repo.

https://github.com/Azure/azure-powershell/issues/14984

**Comment by NowinskiK** [comment]
Thanks.
