### ISSUE TITLE
Sequential or bulk deployment

### ISSUE THREAD

**Issue by PatCwik** [SQLPlayer/azure.datafactory.devops#53]
Hello Kamil,

I am wondering if your tool deploys sequentially or in a bulk deployment mode? Any information would be highly appreciated!

Kind regards,

Patrick

**Comment by NowinskiK** [comment]
Sequentially, object by object. 
But, I don't know what bulk deployment mode is. Could you elaborate?

**Comment by PatCwik** [comment]
Thanks for the quick reply! In essence, I was searching for an easy way to deploy all of our ADF objects in a quick manner. We have about 400-500 pipelines only and you can imagine that a sequential deployment might take some time. So instead of deploying one object at a time, it would be helpful, if i could for example deploy 10 - n pipelines at a time.

**Comment by NowinskiK** [comment]
Right. The deployment of such many objects takes a long time. Unfortunately, the tool does not offer parallel deployment. An alternative is an incremental deployment which will be considered for implementation this year.
Thanks for the clarification.
