### ISSUE TITLE
config.csv file could not find object issue

### ISSUE THREAD

**Issue by MihailEnachi** [SQLPlayer/azure.datafactory.devops#54]
Hi,

I am not able to solve the error ADFT0007: Could not find object:
This relates to Factory(Global Parameters) config type

I created the configuration file as .csv which is being picked up correctly.
![image](https://user-images.githubusercontent.com/87062245/124719487-1b3de500-deff-11eb-9f54-1e03d0c294b5.png)

I get the below error while publishing ADF in the logs
![image](https://user-images.githubusercontent.com/87062245/124719919-8b4c6b00-deff-11eb-843c-b8e04bd5878e.png)

can you please advise where I am going wrong?

**Comment by NowinskiK** [comment]
Check file name in `factory` subfolder. It should named `DWHMode.json` according to your config.

**Comment by MihailEnachi** [comment]
Thanks for pointing me in the right direction.

Error I made was that I was putting the Global parameter name in the "Name" column instead of the factory Name.

Thanks,
Much appreciated
