### ISSUE TITLE
Feature request - select version

### ISSUE THREAD

**Issue by pjtaylor** [SQLPlayer/azure.datafactory.devops#60]
Would be good if we could to do this to control the version we are running on so that we can decide when to implement upgrades instead of always running the latest version? Not sure if Azure Dev Ops supports this...

**Comment by NowinskiK** [comment]
I don't think that feature is available in Azure DevOps. 
You can select and choose the MAJOR version if more are available, but nothing else possible. 
DevOps pipelines always use the latest version available on Marketplace from MAJOR version.

**Comment by NowinskiK** [comment]
If selecting a version is really important in your case - you can use PowerShell module instead of DevOps extension.
In that way, you have full control over which version you install.

**Comment by pjtaylor** [comment]
Thanks, Kamil. Makes sense. We have indeed switched to the PS module as suggested.

**Comment by kaveaa** [comment]
hi, you can not _select_ a minor version but you can specify it in your pipeline like this:

task: BuildADFTask@1.8.937

It is available as long as you did not uninstall the extension from your organization. 
This will give you more control on when you upgrade to a newer task release.

**Comment by NowinskiK** [comment]
Thanks @kaveaa. Good point. 
Is this available only from YAML or from Classic Editor UI as well?
