### ISSUE TITLE
Support Powershell Core

### ISSUE THREAD

**Issue by BenoityipMSFT** [SQLPlayer/azure.datafactory.devops#64]
**Is your feature request related to a problem? Please describe.**
My client does not want to install the old Powershell in the build machine. Only Powershell Core is installed

**Describe the solution you'd like**
A check box in the component to support Powershell Core

**Describe alternatives you've considered**
I am planning to call adf tools powershell script directly in the Powershell Task in Release pipeline, but not sure if it works

**Additional context**

**Comment by NowinskiK** [comment]
Related to #24
