### ISSUE TITLE
Trigger stop/start is all or nothing?

### ISSUE THREAD

**Issue by oramoss** [SQLPlayer/azure.datafactory.devops#7]
Hi Kamil

Came across this tool and it looks interesting for our deployments but I'd like to clarify the stop/start triggers bit. From what I can read of your code, it works on an "all or nothing" basis, i.e. if it's enabled then you stop all triggers before the deployment and restart all triggers afterwards. If we only wanted to restart the triggers which were previously running (and that was a subset of all the triggers), how could we do that? In our current deployments approach we keep a track of what was running and restart only those afterwards...not sure how you do that with this tool...?

**Comment by NowinskiK** [comment]
hi @oramoss.
In that case, I'd recommend to use config file to declare a specific state of trigger per environment.
So, whatever you have in your ADF code - you can change that state (runtimeState property) into desired value, so all "Stopped" triggers won't be enabled (started).
Example of such configuration:
```
type,name,path,value
trigger,TR_AlwaysDisabled,runtimeState,Started
```
I the above case, the trigger gonna be restarted but was stopped in the code.
Let me know if that helps.

**Comment by oramoss** [comment]
Thanks @NowinskiK 
Yes, I think that would work and I like that idea.
