### ISSUE TITLE
Cannot include/exclude objects when DeleteNotInSource

### ISSUE THREAD

**Issue by brianfedorcrowe** [SQLPlayer/azure.datafactory.devops#8]
I really like this script (Publish-AdfV2FromJson). It works like a charm. The only thing I ran into is if I enable the DeleteNotInSource option, then any triggers in the published instance will get removed. We have different triggers set up in the published ADF instance that are not in the develop branch and could see value to including a way to set something like $opt.Excludes.Add("trigger.*", "") or something to that effect to not delete triggers if DeleteNotInSource is enabled.

**Comment by NowinskiK** [comment]
Thanks for your comment.
Is there any particular reason you have a different set of triggers per environment? What if you have the same triggers but switching them on or off depends on the environment?

**Comment by brianfedorcrowe** [comment]
Our application calls an Azure API to create ADF pipeline triggers only for the published instance of ADF, not for the Azure GitOps-based "collaboration" branch. If it were to also create these triggers as part of our ADF repo, then we would eventually have dozens of disabled triggers accumulating there, which we would prefer to avoid. Please let me know this explanation and reasoning is making sense, or if I can provide additional clarification.

**Comment by NowinskiK** [comment]
Thanks for all your comments and feedback. I will definitely consider that kind of option. 
As you noticed - whole stuff is being done by PS module and due to the fact - I will leave open the issue you created in there: https://github.com/SQLPlayer/azure.datafactory.tools/issues/47 and close this issue.
