### ISSUE TITLE
Can not remove or add GlobalParameter using CSV file ?

### ISSUE THREAD

**Issue by StixCoutinho** [SQLPlayer/azure.datafactory.devops#83]
Hi, 
I´m trying to remove and add  global parameters from ADF Target, using de config csv file.

Syntaxes i have tried to REMOVE/DROP a global parameter called "STORAGE_CLIENT_ID"

```
factory,stix-bi-qa-datafactory-tst,"$.properties.globalParameters.'STORAGE_CLIENT_ID'.value","ABC"
factory,stix-bi-qa-datafactory-tst,"$.properties.globalParameters.'STORAGE_CLIENT_ID'.value",""
factory,stix-bi-qa-datafactory-tst,-"$.properties.globalParameters.'STORAGE_CLIENT_ID'.value",""
factory,stix-bi-qa-datafactory-tst,-"$.properties.globalParameters.'STORAGE_CLIENT_ID'.value",
factory,stix-bi-qa-datafactory-tst,"-$.properties.globalParameters.'STORAGE_CLIENT_ID'.value",""
factory,stix-bi-qa-datafactory-tst,"-$.properties.globalParameters.'STORAGE_CLIENT_ID'.value",

```

Syntaxes i have tried to a ADD a new global parameter called "EXAMPLE_PARAMETER"
```
factory,stix-bi-qa-datafactory-tst,+"$.properties.globalParameters.'NEW_EXAMPLE_PARAMETER'.value","123"
factory,stix-bi-qa-datafactory-tst,"+$.properties.globalParameters.'NEW_EXAMPLE_PARAMETER'.value","123"

```

For all these examples, the CSV file was not correct interpreted. I tried to follow examples on link "https://marketplace.visualstudio.com/items?itemName=SQLPlayer.DataFactoryTools"

Could someone provide me the correct syntaxes to add and remove parameters by CSV file? 

Best regards,

Sergio Coutinho

**Comment by NowinskiK** [comment]
Can you try the following syntax:
```
factory,stix-bi-qa-datafactory-tst,-$.properties.globalParameters.STORAGE_CLIENT_ID.value,""
```

**Comment by StixCoutinho** [comment]
[NowinskiK](https://github.com/NowinskiK),

Thank you very for your orientation. I have tried these two options:
```
factory,stix-bi-qa-datafactory-tst,-$.properties.globalParameters.STORAGE_CLIENT_ID.value,
factory,stix-bi-qa-datafactory-tst,-$.properties.globalParameters.STORAGE_CLIENT_ID.value,""
```
But unfortunately, for both options i had the same error:

`2022-02-22T23:03:26.9234050Z ##[error]'Value' cannot be null.`

Is there another syntax option to remove the global parameter?

Best regards,

Sergio

Best regards,

Sergio Coutinho

**Comment by StixCoutinho** [comment]
NowinskiK,

Finaly I could remove the global parameter using this syntax: 

`
factory,stix-bi-dv-datafactory,-$.properties.globalParameters.STORAGE_CLIENT_ID,
`
As I am trying to remove, so i didn´t need to inform ".value" or ".type" in this operation.]

Best regards,

Sergio Coutinho
as

**Comment by NowinskiK** [comment]
Great. Thanks for letting me know! It will help others once they face a similar issue.
