### ISSUE TITLE
No Azure Data Factory files have been found in a given location

### ISSUE THREAD

**Issue by karthikkumarstp1** [SQLPlayer/azure.datafactory.devops#84]
Hello,

I am trying to use the Validate ADF task and getting the following erro

##[error]The property 'Name' cannot be found on this object. Verify that the property exists.

I cannot proceed further and checked all possible options. I am new to ADF pipeline and so any assistance is helpful
![image](https://user-images.githubusercontent.com/100280964/155302193-44eb5be3-48c3-4e2b-8088-6466e4ed7a74.png)

**Comment by NowinskiK** [comment]
As you can see in the log - there are NO files in a given location `D:\a\1\s\AzureDataFactory`.
![image](https://user-images.githubusercontent.com/25029325/155338876-98b925cf-40e7-4428-ad90-ed40f933959f.png)

**Comment by karthikkumarstp1** [comment]
Thanks for the quick response. My folders are at the root level of repo..

![image](https://user-images.githubusercontent.com/100280964/155339846-84faa28b-8347-4e6b-9ed1-588cd7557afe.png)
I tried using the actual repo name and also tried the system.defaultworkingdirectory like below
![image](https://user-images.githubusercontent.com/100280964/155340093-b45f6ffd-c5e1-4046-bbed-d51b77c648bf.png)
If i try the 3 dots and try to navigate, I can select the folders under the repo. Does that mean the entire ADF file need to be under a folder? Thanks in advance for the help

**Comment by NowinskiK** [comment]
Yes, it always easier if ADF has separate folder.
In your case AzureDataFactory IS NOT a folder - it's a name of repo. Try to remove it from path or create such folder in repo.
